### ISSUE TITLE
Error: `Can't find variable: module`

### ISSUE THREAD

**Issue by phillbaker** [sir-dunxalot/broccoli-sass-lint#5]
In projects where QUnit is not a dependency or not loaded into the global namsapce (e.g. ember projects depending exclusively on mocha) the error `Can't find variable: module` is currently thrown.

E.g.
```
not ok 123 PhantomJS 1.9 - TestLoader Failures foo/tests/pages/_bar.sass-lint-test: could not be loaded
    ---
        message: >
            Can't find variable: module
        stack: >
            ReferenceError: Can't find variable: module
```

What do you think about embedded qunit as a dependency and loading it so that it's available for these tests (it looks like jshint does something similar)? Alternatively, we could try detecting if qunit is not available and having tests for the runner or syntax that is available? I can throw together a PR for whichever approach.

**Comment by sir-dunxalot** [comment]
Is this issue occurring when the consuming app's test suite is running or when you're developing this addon somehow? I'm curious to figure out where QUnit is being required from.

`Can't find variable: module` suggests to me that something else might be amiss apart from QUnit.

**Comment by phillbaker** [comment]
@sir-dunxalot thanks for taking a look - the error pops up when running the app's test suite.

As a test, I replaced the `testGenerator` function with a mocha based one:
```
SassLinter.prototype.testGenerator = function(relativePath, errors) {
    if (errors) {
      errors = this.escapeErrorString('\n' + errors);
    }
    return "describe('Sass Lint - " + path.dirname(relativePath) + "', function() { \n" +
            "it('" + relativePath + " should pass sass-lint', function() {\n" +
            "expect(" + (errors.search(/problem(s)? \(\d+ error/i)) + ").to.be.false;\n" +
            "});\n" +
            "});\n";
};
```
which worked as expected.
